In [ ]:
import pandas as pd
import numpy as np
import math

In [ ]:
pd.DataFrame({"col1": [1,2,3,4,5],
              "col2": [23,34,45,56,44],
              "col3" : "shudh kumar krish class one"})



col1  col2                         col3
0     1    23  shudh kumar krish class one
1     2    34  shudh kumar krish class one
2     3    45  shudh kumar krish class one
3     4    56  shudh kumar krish class one
4     5    44  shudh kumar krish class one

In [ ]:
# if i m expecting all ewords in last col3 to be in seperatee columns


In [ ]:
# split function
"shudh kumar krish study one".split()

['shudh', 'kumar', 'krish', 'study', 'one']

In [ ]:
df = pd.DataFrame({"col1": [1,2,3,4,5],
              "col2": [23,34,45,56,44],
              "col3" : "shudh kmr krishna class one".split()  # default delimiter is pace " "
              })



In [ ]:
# creating col4
df['col4'] = 1
df

col1  col2     col3  col4
0     1    23    shudh     1
1     2    34      kmr     1
2     3    45  krishna     1
3     4    56    class     1
4     5    44      one     1

In [ ]:
df['col4'] = df['col1']**2
df

col1  col2     col3  col4
0     1    23    shudh     1
1     2    34      kmr     4
2     3    45  krishna     9
3     4    56    class    16
4     5    44      one    25

In [ ]:
# col5 holding 1st char of column 3
df['col5'] = df['col3'].str[0]
df

col1  col2     col3  col4 col5
0     1    23    shudh     1    s
1     2    34      kmr     4    k
2     3    45  krishna     9    k
3     4    56    class    16    c
4     5    44      one    25    o

In [ ]:
def test(a):
  return a*a

df['col4_4'] = df['col1'].apply(test)
df
# axis = 0 row level
# axis = 1 column level

col1  col2     col3  col4 col5  col4_4
0     1    23    shudh     1    s       1
1     2    34      kmr     4    k       4
2     3    45  krishna     9    k       9
3     4    56    class    16    c      16
4     5    44      one    25    o      25

In [ ]:
def tst(xyz):
  if xyz[0] == "s":
    return xyz[0]
  else:
    return 'z'

df['col6'] = df['col5'].apply(tst)
df

col1  col2     col3  col4 col5  col4_4 col6
0     1    23    shudh     1    s       1    s
1     2    34      kmr     4    k       4    z
2     3    45  krishna     9    k       9    z
3     4    56    class    16    c      16    z
4     5    44      one    25    o      25    z

In [ ]:
# another way
# list comprihension

df['col6_6'] = df['col5'].apply(lambda x : 's' if x == 's' else 'z')
df

col1  col2     col3  col4 col5  col4_4 col6 col6_6
0     1    23    shudh     1    s       1    s      s
1     2    34      kmr     4    k       4    z      z
2     3    45  krishna     9    k       9    z      z
3     4    56    class    16    c      16    z      z
4     5    44      one    25    o      25    z      z

In [ ]:
df['col7']  = df['col3'].apply(len)

In [ ]:
df

col1  col2     col3  col4 col5  col4_4 col6 col6_6  col7
0     1    23    shudh     1    s       1    s      s     5
1     2    34      kmr     4    k       4    z      z     3
2     3    45  krishna     9    k       9    z      z     7
3     4    56    class    16    c      16    z      z     5
4     5    44      one    25    o      25    z      z     3

In [ ]:
import math

df['col8'] = df['col2'].apply(math.log)
df

col1  col2     col3  col4 col5  col4_4 col6 col6_6  col7      col8
0     1    23    shudh     1    s       1    s      s     5  3.135494
1     2    34      kmr     4    k       4    z      z     3  3.526361
2     3    45  krishna     9    k       9    z      z     7  3.806662
3     4    56    class    16    c      16    z      z     5  4.025352
4     5    44      one    25    o      25    z      z     3  3.784190

In [ ]:
# array format manupulationws operations

In [ ]:
import numpy as np


In [ ]:
l = ['sudh',2,3,4,5,6]
type(l)

list

In [ ]:
np.array(l)

array(['sudh', '2', '3', '4', '5', '6'], dtype='<U21')

In [ ]:
type(np.array(l))

numpy.ndarray

In [ ]:
np.array([3.5,4,2,3,65,7,98,6])

array([ 3.5,  4. ,  2. ,  3. , 65. ,  7. , 98. ,  6. ])

In [ ]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [ ]:
type(a)


numpy.ndarray

In [ ]:
# indexing in aRRAY

a[1][1]

np.int64(4)

In [ ]:
a1 = np.array([3.5,4,2,3,65,7,98,6])
a1

array([ 3.5,  4. ,  2. ,  3. , 65. ,  7. , 98. ,  6. ])

In [ ]:
a1[2]

np.float64(2.0)

In [ ]:
# ndmin = num set the dimention of the array


In [ ]:
np.array([1,2,3,4], ndmin= 0)

array([1, 2, 3, 4])

In [ ]:
np.array([1,2,3,4], ndmin= 1)

array([1, 2, 3, 4])

In [ ]:
np.array([1,2,3,4], ndmin= 2)

array([[1, 2, 3, 4]])

In [ ]:
np.array([1,2,3,4], ndmin= 3)

array([[[1, 2, 3, 4]]])

In [ ]:
np.array([1,2,3,4], ndmin= 4)

array([[[[1, 2, 3, 4]]]])

In [ ]:
type(np.array([1,2,3,4], ndmin= 4))

numpy.ndarray

In [ ]:
a2 = np.array([17,2,3,4], ndmin= 4)
# try t oget 17 out of this a2
a2

array([[[[17,  2,  3,  4]]]])

In [ ]:
a2[0][0][0][0]

np.int64(17)

In [ ]:
# data representatio \
#

# y-axis
# ^
# |
# |     -----------------
# |     |    1  |   2   |
# |     |       |       |
# |     | --------------|
# |     |       |       |
# |     |    3  |   4   |
# |     |---------------|
# |
# |------------------------> x-axis


# this is 2 dimetional data

In [ ]:
np.asarray([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [ ]:

np.asanyarray([1,2,3,4,6,7,8,5])

array([1, 2, 3, 4, 6, 7, 8, 5])

In [ ]:
# matrix

In [ ]:
np.asmatrix([1,2,3,4,5])
# at min must have 2 dimention data
# even if we pass 1 d list it will retrun 2-D data by default

matrix([[1, 2, 3, 4, 5]])

In [ ]:
a = [1,2,3,4,5,6,7,8]

np.asarray(a)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.asmatrix(a)

matrix([[1, 2, 3, 4, 5, 6, 7, 8]])

In [ ]:
np.asanyarray(a)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.asanyarray(np.asmatrix(a))

# matrix is child of array
# asanyarray( will check if ithe passed thing is already a form of an arrray)
#$ for asany array
# if something is not avilable in array format it will convert it into array ofrmat
# if something is already in array format it will keep it as it is

matrix([[1, 2, 3, 4, 5, 6, 7, 8]])

In [ ]:
# making array of different dimention

In [ ]:
np.fromfunction(lambda i,j : i==j , (3,3))
# (3,3) 3x3 matrix creation = dimention = 3
# i = row
# j = column
# he condition in funciotn  => i == j

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
np.fromfunction(lambda x,y  : x!=y ,(5,5))

array([[False,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True,  True,  True, False]])

In [ ]:
np.fromfunction(lambda i,j : i*j, (4,4))


# output :
#      0     1    2     3
# 0 [[0x0, 0x1,  0x2, 0x3],

# 1  [1x0, 1x1,  1x2, 1x3],

# 2  [2x0, 2x1,  2x2, 2x3],

# 3  [3x0, 3x1,  3x2, 3x3]]

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [ ]:
# all the elementrs in the matriz are floate
# to get different dtype

In [ ]:
np.fromfunction(lambda x,y : x*y, (5,5), dtype=int)

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16]])

In [ ]:
# if we try to pass 3 arguments
# 3-D data

np.fromfunction(lambda i,j,k : i*j*k, (3,3,3), dtype=int)


# output :
#         0        1       2        0th matrix/array
# 0 [ [ [0x0x0, 0x0x1,  0x0x2],

# 1     [0x1x0, 0x1x1,  0x1x2],

# 2     [0x2x0, 0x2x1,  0x2x2] ]


#         0        1       2        1st matrix/array
# 0   [ [1x0x0, 1x0x1,  1x0x2],

# 1     [1x1x0, 1x1x1,  1x1x2],

# 2     [1x2x0, 1x2x1,  1x2x2] ]

#         0        1       2        2ndth matrix/array
# 0   [ [2x0x0, 2x0x1,  2x0x2],

# 1     [2x1x0, 2x1x1,  2x1x2],

# 2     [2x2x0, 2x2x1,  2x2x2]  ]  ]


array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 2],
        [0, 2, 4]],

       [[0, 0, 0],
        [0, 2, 4],
        [0, 4, 8]]])

In [ ]:
np.fromfunction(lambda i,j,k : i*j*k, (3,3,2), dtype = int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [ ]:
np.fromfunction(lambda p,q,r,s : p*q*r*s , (4,3,2,2), dtype = int)
# -----------------------------------------     [2x2]array/matrices
# --------------------------------------------3  (2x2) array one b3ehind another like pages
# ------------------------------------------ 4 combination

# so basically we have   3 (2x2) array with 4 bundle(or)combination

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

In [ ]:
a = np.fromfunction(lambda i,j,k : i*j*k , (4,3,2) , dtype = int)
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [ ]:
a.ndim
# dimention ofd the array
# i,e, number of axis the matrix/array have

3

In [ ]:
a.size
# size of the array
# i.e. number of elements does array contian

24

In [ ]:
a.shape
# 4 (3x2) array

(4, 3, 2)

In [ ]:
a.dtype
# in numpy there are int16 bit, int32 bit and int 64 bit array
# we have int 64

dtype('int64')

In [ ]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [ ]:
# convera into dataframe

df = pd.DataFrame(a) # it needs 2-D array only

# we need to reshape or flaten it

ValueError: Must pass 2-d input. shape=(4, 3, 2)

In [ ]:
a =np.fromfunction(lambda i,j : i*j , (4,3), dtype = int)
print(a,"/n/n====================================\n\n")

df1 = pd.DataFrame(a)
df1

[[0 0 0]
 [0 1 2]
 [0 2 4]
 [0 3 6]] /n/n====================================




0  1  2
0  0  0  0
1  0  1  2
2  0  2  4
3  0  3  6

In [ ]:
# to create you own data set
a =np.fromfunction(lambda i,j : i*j , (400,30), dtype = int)
print(a,"/n/n====================================\n\n")

df1 = pd.DataFrame(a)
df1

[[    0     0     0 ...     0     0     0]
 [    0     1     2 ...    27    28    29]
 [    0     2     4 ...    54    56    58]
 ...
 [    0   397   794 ... 10719 11116 11513]
 [    0   398   796 ... 10746 11144 11542]
 [    0   399   798 ... 10773 11172 11571]] /n/n====================================




0    1    2     3     4     5     6     7     8     9   ...    20    21  \
0     0    0    0     0     0     0     0     0     0     0  ...     0     0   
1     0    1    2     3     4     5     6     7     8     9  ...    20    21   
2     0    2    4     6     8    10    12    14    16    18  ...    40    42   
3     0    3    6     9    12    15    18    21    24    27  ...    60    63   
4     0    4    8    12    16    20    24    28    32    36  ...    80    84   
..   ..  ...  ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   ...   
395   0  395  790  1185  1580  1975  2370  2765  3160  3555  ...  7900  8295   
396   0  396  792  1188  1584  1980  2376  2772  3168  3564  ...  7920  8316   
397   0  397  794  1191  1588  1985  2382  2779  3176  3573  ...  7940  8337   
398   0  398  796  1194  1592  1990  2388  2786  3184  3582  ...  7960  8358   
399   0  399  798  1197  1596  1995  2394  2793  3192  3591  ...  7980  8379   

       22    23    24    25     26     27     28     29  
0       0     0     0     0      0      0      0      0  
1      22    23    24    25     26     27     28     29  
2      44    46    48    50     52     54     56     58  
3      66    69    72    75     78     81     84     87  
4      88    92    96   100    104    108    112    116  
..    ...   ...   ...   ...    ...    ...    ...    ...  
395  8690  9085  9480  9875  10270  10665  11060  11455  
396  8712  9108  9504  9900  10296  10692  11088  11484  
397  8734  9131  9528  9925  10322  10719  11116  11513  
398  8756  9154  9552  9950  10348  10746  11144  11542  
399  8778  9177  9576  9975  10374  10773  11172  11571  

[400 rows x 30 columns]

In [ ]:
# create random data and convert it into dataframe


In [ ]:
np.random.rand(100,5)  # rand(rows, columns)

array([[0.29631222, 0.79748421, 0.75533495, 0.01873451, 0.58231975],
       [0.83060813, 0.60487864, 0.13284248, 0.75072651, 0.73974074],
       [0.697592  , 0.33334964, 0.27006316, 0.30522837, 0.13626199],
       [0.18993009, 0.22662138, 0.59974264, 0.16645118, 0.92513796],
       [0.35882572, 0.6479517 , 0.35000937, 0.76791767, 0.94225477],
       [0.6096097 , 0.50024614, 0.08862758, 0.44713498, 0.65854062],
       [0.33993629, 0.93278345, 0.98413018, 0.79772584, 0.60948428],
       [0.67680612, 0.04561752, 0.2697207 , 0.40980803, 0.71135976],
       [0.77027003, 0.52524783, 0.18566597, 0.62271694, 0.3611999 ],
       [0.2390821 , 0.9743406 , 0.42517397, 0.63948692, 0.4660405 ],
       [0.14253746, 0.78052602, 0.1416232 , 0.03807466, 0.84918417],
       [0.01505531, 0.04188975, 0.42471277, 0.05241337, 0.12380313],
       [0.98367288, 0.99299914, 0.8478894 , 0.64468979, 0.59189806],
       [0.58728214, 0.67214659, 0.24898828, 0.7899267 , 0.52257708],
       [0.72523452, 0.7291873 , 0.

In [ ]:
pd.DataFrame(np.random.rand(100,5))

0         1         2         3         4
0   0.468932  0.364586  0.417902  0.359625  0.496143
1   0.407548  0.186982  0.855019  0.812029  0.784046
2   0.187696  0.973429  0.322062  0.494989  0.805839
3   0.955313  0.638858  0.484364  0.573098  0.332850
4   0.593318  0.509122  0.585551  0.799017  0.576094
..       ...       ...       ...       ...       ...
95  0.346750  0.708798  0.559378  0.902957  0.704470
96  0.033411  0.596662  0.340294  0.555476  0.772922
97  0.972749  0.894685  0.912116  0.956383  0.888677
98  0.957004  0.759670  0.807971  0.830252  0.344215
99  0.059827  0.692741  0.239020  0.099248  0.296327

[100 rows x 5 columns]

In [ ]:
# another funciton
np.random.randint(4,50) # show random int in provided range
# ranint() : always gives you a simple random number


42

In [ ]:
np.random.randn(4,5)

# randn() : always give random number, but with normal distribution
#          i.e. the avg of all the numbers generated by rand() = 0 and
#                       stan. dev. = 1


array([[ 0.49811244, -0.36154666,  0.41345368,  0.94042849,  0.92727019],
       [ 0.79143667, -0.23842819, -1.35390627,  0.73259105,  0.76618512],
       [-1.30152886, -0.68911911, -0.97924764, -1.67609227, -0.03569334],
       [ 0.0429558 ,  1.79189575, -0.2575435 ,  0.07949753,  0.46404719]])

In [ ]:
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0 -0.342206  1.145917 -0.317255  0.509671 -1.505596
1 -0.459857  1.501350 -0.797545  0.671364  0.601543
2 -0.113582  1.190211 -0.098266 -1.112839  0.426142
3  0.031465  1.338828  0.433501  0.828926 -0.449391

In [ ]:
# ranint() : always gives you a simple random number
# randn() : always give random number, but with normal distribution
#          i.e. the avg of all the numbers generated by rand() = 0 and
#                       stan. dev. = 1



In [ ]:
a = np.fromfunction(lambda i,j,k : i*j*k ,(4,3,2), dtype=int)

pd.DataFrame(a)

ValueError: Must pass 2-d input. shape=(4, 3, 2)

In [ ]:
# to convert hte data ab0ve into 2_d to fit into a dataframe

a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [ ]:
a.reshape(3,8)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 2, 0, 0, 0, 2],
       [0, 4, 0, 0, 0, 3, 0, 6]])

In [ ]:
a.reshape(12,2)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 2],
       [0, 0],
       [0, 2],
       [0, 4],
       [0, 0],
       [0, 3],
       [0, 6]])

In [ ]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [ ]:
b = a.reshape(8,3)
pd.DataFrame(b)

0  1  2
0  0  0  0
1  0  0  0
2  0  0  0
3  1  0  2
4  0  0  0
5  2  0  4
6  0  0  0
7  3  0  6

In [ ]:
# to convet a 3-D into 4-D data

a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [ ]:
a.reshape(4,1,2,3)

array([[[[0, 0, 0],
         [0, 0, 0]]],


       [[[0, 0, 0],
         [1, 0, 2]]],


       [[[0, 0, 0],
         [2, 0, 4]]],


       [[[0, 0, 0],
         [3, 0, 6]]]])

In [ ]:
# a has 24 elements
# what does the -1 do ?
# => by default (given num) 4 x ? is gonna be 24
#                           4 x ? = 24
# what ever is the answer will be considered and then the array we get will be 4 x 6
# 6 cox here the answer in place of questionmark is 6

a.reshape(4,-1)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4],
       [0, 0, 0, 3, 0, 6]])

In [ ]:
a.reshape(5,-1)
# it will not work with 5 coz
# 5 x anything is not 24

ValueError: cannot reshape array of size 24 into shape (5,newaxis)

In [ ]:
a.reshape(2,-1)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4, 0, 0, 0, 3, 0, 6]])

In [ ]:
a.reshape(8,-3423532)
# the 2nd arg dosnt hv to be -1, it could be any -ve number


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 2],
       [0, 0, 0],
       [2, 0, 4],
       [0, 0, 0],
       [3, 0, 6]])

In [ ]:
a.reshape(3,4,-38476983745092384)
# it will take 3 x 4 x 2

array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 1],
        [0, 2],
        [0, 0],
        [0, 2]],

       [[0, 4],
        [0, 0],
        [0, 3],
        [0, 6]]])

In [ ]:

list(range(4,15))

[4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [ ]:
np.arange(4,12,0.2)  # arange() is same as range() function
# the only differenc is here u can give floating point step value

array([ 4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,
        6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,
        8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4,
       10.6, 10.8, 11. , 11.2, 11.4, 11.6, 11.8])

In [ ]:
a1 = np.arange(1,12.6,0.2)

In [ ]:
a1[1:4] # same slicing operation

array([1.2, 1.4, 1.6])

In [ ]:
arr =  np.random.rand(4,5)
arr
# try to extract all the numbers that are greater than 0.5

array([[0.20458686, 0.46832375, 0.98580594, 0.30373436, 0.26766732],
       [0.64461048, 0.82896062, 0.65058472, 0.39165967, 0.03274944],
       [0.25043178, 0.13920296, 0.74070542, 0.84277876, 0.6545395 ],
       [0.86891977, 0.05530578, 0.15068901, 0.43636422, 0.1808485 ]])

In [ ]:
arr1 = arr[arr > 0.5]
arr1

array([0.98580594, 0.64461048, 0.82896062, 0.65058472, 0.74070542,
       0.84277876, 0.6545395 , 0.86891977])

In [ ]:
arr

array([[0.20458686, 0.46832375, 0.98580594, 0.30373436, 0.26766732],
       [0.64461048, 0.82896062, 0.65058472, 0.39165967, 0.03274944],
       [0.25043178, 0.13920296, 0.74070542, 0.84277876, 0.6545395 ],
       [0.86891977, 0.05530578, 0.15068901, 0.43636422, 0.1808485 ]])

In [ ]:
arr.shape

(4, 5)

In [ ]:
arr[[[1,2]],[2]]
# array_name [ [[rows]], [column] ]

array([[0.65058472, 0.74070542]])

In [ ]:
arr2 = [arr[1,2], arr[1,2], arr[2,2], arr[2,3]]
arr2

[np.float64(0.6505847214853714),
 np.float64(0.6505847214853714),
 np.float64(0.7407054185939828),
 np.float64(0.84277876010645)]

In [ ]:
arr[1][2]

np.float64(0.6505847214853714)

In [ ]:
# new array

arr = np.random.rand(8,5)
arr

array([[0.19608465, 0.53649415, 0.91562853, 0.10692424, 0.21374855],
       [0.55963121, 0.21450996, 0.69221558, 0.37087331, 0.55068742],
       [0.89389247, 0.92632778, 0.07367481, 0.46162154, 0.17755116],
       [0.93912323, 0.23576768, 0.46820607, 0.51526491, 0.46725265],
       [0.33836419, 0.14692209, 0.71483401, 0.97295366, 0.4823791 ],
       [0.30463753, 0.61459606, 0.63451863, 0.44001902, 0.92699707],
       [0.61260933, 0.40326375, 0.65273676, 0.40256988, 0.55234784],
       [0.80997258, 0.39805828, 0.46784934, 0.3980523 , 0.38552173]])

In [ ]:

arr[1:8,0:3]

array([[0.55963121, 0.21450996, 0.69221558],
       [0.89389247, 0.92632778, 0.07367481],
       [0.93912323, 0.23576768, 0.46820607],
       [0.33836419, 0.14692209, 0.71483401],
       [0.30463753, 0.61459606, 0.63451863],
       [0.61260933, 0.40326375, 0.65273676],
       [0.80997258, 0.39805828, 0.46784934]])

In [ ]:
arr3 = arr[1:8, [0,1,2]]
arr3

array([[0.55963121, 0.21450996, 0.69221558],
       [0.89389247, 0.92632778, 0.07367481],
       [0.93912323, 0.23576768, 0.46820607],
       [0.33836419, 0.14692209, 0.71483401],
       [0.30463753, 0.61459606, 0.63451863],
       [0.61260933, 0.40326375, 0.65273676],
       [0.80997258, 0.39805828, 0.46784934]])

In [ ]:
arr3[0][0]

np.float64(0.5596312090837091)

In [ ]:
arr3[0][0] = 100
arr3

array([[1.00000000e+02, 2.14509959e-01, 6.92215577e-01],
       [8.93892467e-01, 9.26327779e-01, 7.36748062e-02],
       [9.39123233e-01, 2.35767680e-01, 4.68206075e-01],
       [3.38364191e-01, 1.46922088e-01, 7.14834009e-01],
       [3.04637530e-01, 6.14596064e-01, 6.34518627e-01],
       [6.12609327e-01, 4.03263753e-01, 6.52736757e-01],
       [8.09972578e-01, 3.98058283e-01, 4.67849344e-01]])

In [ ]:
a = np.array([[1,1], [1,1]])
b = np.array([[2,3], [4,5]])

a * b

array([[2, 3],
       [4, 5]])

In [ ]:
# convert ELEMENT WISE  multiplication
a * b

array([[2, 3],
       [4, 5]])

In [ ]:
a = np.array([[1,2], [3,4]])
b = np.array([[3,4], [5,6]])
b

array([[3, 4],
       [5, 6]])

In [ ]:
# matrix multiplication

m = a@b

In [ ]:
# Actual matrix multiplication
# ___                __
# |                                      |      [[1,2]     [[3,4]
# |  [1x3 + 2x5]          [1x4 + 2x6]    |      [3,4]]     [5,6]]
# |  =[3+10] = 13          = 16          |
# |                                      |
# | [3x3 + 4x5]            [3x4 + 4x6]   |       multiply [1,2] x [ 3,5]  ==   [1x3 + 2x5]                    |                 |
# | = [9 + 20] = 29         = 36         |       multiply [1,2] x [ 4,6]  ==   [1x4 + 2x6]
# |                                      |        =========================================
# |__                                  __|       mulriply [3,4] x [3,5]   ==   [3x3 + 4x5]
#                                                mulriply [3,4] x [4,6]   ==   [3x4 + 4x6]

In [ ]:
m/0  # in numpy mathematically it is infinity

<ipython-input-103-4e0165db520a>:1: RuntimeWarning: divide by zero encountered in divide
  m/0  # in numpy mathematically it is infinity


array([[inf, inf],
       [inf, inf]])

In [ ]:
34/0

ZeroDivisionError: division by zero

In [ ]:
######################################################
### #### ##      ###############################################
### # ## ## ####  #############################################
### ## # ## ###### ############################################
### ###  ###     ##################################################
#####################################################################

In [ ]:
import numpy as np

In [ ]:
from re import L
l = [1,2,3,4,5]
np.asarray(l)


array([1, 2, 3, 4, 5])

In [ ]:
np.zeros(5)  #v generatesc an array of length 5 contain all zeros

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(5)  # smae thing as zeroez but ones\


array([1., 1., 1., 1., 1.])

In [ ]:
# multidim array

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:

np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# we sometime uise to fill the data lik rgb colors or flat data/

In [ ]:
np.ones((3,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
5 + np.zeros((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
a = np.empty((4,5))
# it generates random values with very slamm values
# these are ery very small values
# 0.something


a

array([[0.20458686, 0.46832375, 0.98580594, 0.30373436, 0.26766732],
       [0.64461048, 0.82896062, 0.65058472, 0.39165967, 0.03274944],
       [0.25043178, 0.13920296, 0.74070542, 0.84277876, 0.6545395 ],
       [0.86891977, 0.05530578, 0.15068901, 0.43636422, 0.1808485 ]])

In [ ]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.empty((5,4))

array([[0.20458686, 0.46832375, 0.98580594, 0.30373436],
       [0.26766732, 0.64461048, 0.82896062, 0.65058472],
       [0.39165967, 0.03274944, 0.25043178, 0.13920296],
       [0.74070542, 0.84277876, 0.6545395 , 0.86891977],
       [0.05530578, 0.15068901, 0.43636422, 0.1808485 ]])

In [ ]:
np.empty((5,4,2))

array([[[0.19608465, 0.53649415],
        [0.91562853, 0.10692424],
        [0.21374855, 0.55963121],
        [0.21450996, 0.69221558]],

       [[0.37087331, 0.55068742],
        [0.89389247, 0.92632778],
        [0.07367481, 0.46162154],
        [0.17755116, 0.93912323]],

       [[0.23576768, 0.46820607],
        [0.51526491, 0.46725265],
        [0.33836419, 0.14692209],
        [0.71483401, 0.97295366]],

       [[0.4823791 , 0.30463753],
        [0.61459606, 0.63451863],
        [0.44001902, 0.92699707],
        [0.61260933, 0.40326375]],

       [[0.65273676, 0.40256988],
        [0.55234784, 0.80997258],
        [0.39805828, 0.46784934],
        [0.3980523 , 0.38552173]]])

In [ ]:
# some inbuilt funcitons


In [ ]:
np.linspace(2,6)
# syntax
# np.linespace(start_point , end_point, number of elements)  =

# it it take start and end and generate values in between
# we can mention how many numbers do we want in between
# it generates single dim only
# it considers the upper bound as well
# the upper bound is not excluded

array([2.        , 2.08163265, 2.16326531, 2.24489796, 2.32653061,
       2.40816327, 2.48979592, 2.57142857, 2.65306122, 2.73469388,
       2.81632653, 2.89795918, 2.97959184, 3.06122449, 3.14285714,
       3.2244898 , 3.30612245, 3.3877551 , 3.46938776, 3.55102041,
       3.63265306, 3.71428571, 3.79591837, 3.87755102, 3.95918367,
       4.04081633, 4.12244898, 4.20408163, 4.28571429, 4.36734694,
       4.44897959, 4.53061224, 4.6122449 , 4.69387755, 4.7755102 ,
       4.85714286, 4.93877551, 5.02040816, 5.10204082, 5.18367347,
       5.26530612, 5.34693878, 5.42857143, 5.51020408, 5.59183673,
       5.67346939, 5.75510204, 5.83673469, 5.91836735, 6.        ])

In [ ]:
# with the number of elements mentioned

np.linspace(2,6,100)

array([2.        , 2.04040404, 2.08080808, 2.12121212, 2.16161616,
       2.2020202 , 2.24242424, 2.28282828, 2.32323232, 2.36363636,
       2.4040404 , 2.44444444, 2.48484848, 2.52525253, 2.56565657,
       2.60606061, 2.64646465, 2.68686869, 2.72727273, 2.76767677,
       2.80808081, 2.84848485, 2.88888889, 2.92929293, 2.96969697,
       3.01010101, 3.05050505, 3.09090909, 3.13131313, 3.17171717,
       3.21212121, 3.25252525, 3.29292929, 3.33333333, 3.37373737,
       3.41414141, 3.45454545, 3.49494949, 3.53535354, 3.57575758,
       3.61616162, 3.65656566, 3.6969697 , 3.73737374, 3.77777778,
       3.81818182, 3.85858586, 3.8989899 , 3.93939394, 3.97979798,
       4.02020202, 4.06060606, 4.1010101 , 4.14141414, 4.18181818,
       4.22222222, 4.26262626, 4.3030303 , 4.34343434, 4.38383838,
       4.42424242, 4.46464646, 4.50505051, 4.54545455, 4.58585859,
       4.62626263, 4.66666667, 4.70707071, 4.74747475, 4.78787879,
       4.82828283, 4.86868687, 4.90909091, 4.94949495, 4.98989

In [ ]:
np.linspace(1,5,10)

# div complete scale that many times

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
# conerting this into 2-D

np.linspace(1,6,20).reshape(5,4)  # it considers the upperbound as well
# reshape has to have this condition met
# 5 x 4 = 20
# number of elements = reshape dimention

array([[1.        , 1.26315789, 1.52631579, 1.78947368],
       [2.05263158, 2.31578947, 2.57894737, 2.84210526],
       [3.10526316, 3.36842105, 3.63157895, 3.89473684],
       [4.15789474, 4.42105263, 4.68421053, 4.94736842],
       [5.21052632, 5.47368421, 5.73684211, 6.        ]])

In [ ]:
# to exclue the upper bound we hv to make the " 'endpoint' = False " as a param
# by default the endpoint param is True

In [ ]:
np.linspace(2,6,10, endpoint=False).reshape(5,2)
# see now the upper bound 6 is excluded

array([[2. , 2.4],
       [2.8, 3.2],
       [3.6, 4. ],
       [4.4, 4.8],
       [5.2, 5.6]])

In [ ]:
np.linspace(2,6,10).reshape(5,2)
# this time 6 the upper bound is included
# this is coz the endpoint param is True

array([[2.        , 2.44444444],
       [2.88888889, 3.33333333],
       [3.77777778, 4.22222222],
       [4.66666667, 5.11111111],
       [5.55555556, 6.        ]])

In [ ]:
# to eliminate the lower bount we can till use slicing

In [ ]:
# linspace() never takes a step size
# but it uses it to generate data inernally
# to find the step size linspace is using :
# there is a param "retspet"
# if = True it show step size at the end

np.linspace(2,6,10, endpoint=False, retstep = True)

 # as we can see the step size is 0.4

(array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2, 5.6]), np.float64(0.4))

In [ ]:
np.linspace(2,6,100, endpoint=False, retstep = True)
# step size = 0.04

(array([2.  , 2.04, 2.08, 2.12, 2.16, 2.2 , 2.24, 2.28, 2.32, 2.36, 2.4 ,
        2.44, 2.48, 2.52, 2.56, 2.6 , 2.64, 2.68, 2.72, 2.76, 2.8 , 2.84,
        2.88, 2.92, 2.96, 3.  , 3.04, 3.08, 3.12, 3.16, 3.2 , 3.24, 3.28,
        3.32, 3.36, 3.4 , 3.44, 3.48, 3.52, 3.56, 3.6 , 3.64, 3.68, 3.72,
        3.76, 3.8 , 3.84, 3.88, 3.92, 3.96, 4.  , 4.04, 4.08, 4.12, 4.16,
        4.2 , 4.24, 4.28, 4.32, 4.36, 4.4 , 4.44, 4.48, 4.52, 4.56, 4.6 ,
        4.64, 4.68, 4.72, 4.76, 4.8 , 4.84, 4.88, 4.92, 4.96, 5.  , 5.04,
        5.08, 5.12, 5.16, 5.2 , 5.24, 5.28, 5.32, 5.36, 5.4 , 5.44, 5.48,
        5.52, 5.56, 5.6 , 5.64, 5.68, 5.72, 5.76, 5.8 , 5.84, 5.88, 5.92,
        5.96]),
 np.float64(0.04))

In [ ]:
np.logspace(2,6)

# it is similer to linspace but
# it gives us logorithmic space

array([1.00000000e+02, 1.20679264e+02, 1.45634848e+02, 1.75751062e+02,
       2.12095089e+02, 2.55954792e+02, 3.08884360e+02, 3.72759372e+02,
       4.49843267e+02, 5.42867544e+02, 6.55128557e+02, 7.90604321e+02,
       9.54095476e+02, 1.15139540e+03, 1.38949549e+03, 1.67683294e+03,
       2.02358965e+03, 2.44205309e+03, 2.94705170e+03, 3.55648031e+03,
       4.29193426e+03, 5.17947468e+03, 6.25055193e+03, 7.54312006e+03,
       9.10298178e+03, 1.09854114e+04, 1.32571137e+04, 1.59985872e+04,
       1.93069773e+04, 2.32995181e+04, 2.81176870e+04, 3.39322177e+04,
       4.09491506e+04, 4.94171336e+04, 5.96362332e+04, 7.19685673e+04,
       8.68511374e+04, 1.04811313e+05, 1.26485522e+05, 1.52641797e+05,
       1.84206997e+05, 2.22299648e+05, 2.68269580e+05, 3.23745754e+05,
       3.90693994e+05, 4.71486636e+05, 5.68986603e+05, 6.86648845e+05,
       8.28642773e+05, 1.00000000e+06])

In [ ]:
np.logspace(2,4,10)


array([  100.        ,   166.81005372,   278.25594022,   464.15888336,
         774.26368268,  1291.54966501,  2154.43469003,  3593.8136638 ,
        5994.84250319, 10000.        ])

In [ ]:
# we can also mention the base
np.logspace(2,4,10, base = 10)

array([  100.        ,   166.81005372,   278.25594022,   464.15888336,
         774.26368268,  1291.54966501,  2154.43469003,  3593.8136638 ,
        5994.84250319, 10000.        ])

In [ ]:
np.logspace(2,4,10, base = 2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [ ]:
np.linspace(2,4,10)

array([2.        , 2.22222222, 2.44444444, 2.66666667, 2.88888889,
       3.11111111, 3.33333333, 3.55555556, 3.77777778, 4.        ])

In [ ]:
a = np.arange(2,8.20)
a

array([2., 3., 4., 5., 6., 7., 8.])

In [ ]:
a = np.arange(16) # upper bound is excluded
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
a.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
a = np.arange(4,20).reshape(4,4)
a

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
a.max()  # max element

np.int64(19)

In [ ]:
a = np.arange(4,40).reshape(3,6,2)
a  # remeber that
#     40-4 = 36 = 3*6*2

array([[[ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [ ]:
a.max

<function ndarray.max>

In [ ]:
# there is a param max in the max function

a.max(axis = 1)   # be default it was row wise search coz axis = 0
# axis = 1 == column wise search

# so we r getting max array from each of the 3 bunches of (6x2) array

array([ 9, 15, 21, 27, 33, 39])

In [ ]:
a = np.arange(4,40).reshape(6,6)
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [ ]:
a.max()  # max element

np.int64(39)

In [ ]:
a.max(axis = 0) # row wise we get row with max number
# axs = 0 row

array([34, 35, 36, 37, 38, 39])

In [ ]:
a.max(axis = 1 )
# column wise we get column witrh max number

array([ 9, 15, 21, 27, 33, 39])

In [ ]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [ ]:
10 + a

array([[14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [ ]:
10 * a

array([[ 40,  50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200, 210],
       [220, 230, 240, 250, 260, 270],
       [280, 290, 300, 310, 320, 330],
       [340, 350, 360, 370, 380, 390]])

In [ ]:
a / 2  # division of matrix elemntwise

array([[ 2. ,  2.5,  3. ,  3.5,  4. ,  4.5],
       [ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5],
       [ 8. ,  8.5,  9. ,  9.5, 10. , 10.5],
       [11. , 11.5, 12. , 12.5, 13. , 13.5],
       [14. , 14.5, 15. , 15.5, 16. , 16.5],
       [17. , 17.5, 18. , 18.5, 19. , 19.5]])

In [ ]:
a ** 2 # sq

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]])

In [ ]:
pow(a,2) # squre

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]])

In [ ]:
pow(a,3) # cube

array([[   64,   125,   216,   343,   512,   729],
       [ 1000,  1331,  1728,  2197,  2744,  3375],
       [ 4096,  4913,  5832,  6859,  8000,  9261],
       [10648, 12167, 13824, 15625, 17576, 19683],
       [21952, 24389, 27000, 29791, 32768, 35937],
       [39304, 42875, 46656, 50653, 54872, 59319]])

In [ ]:
b = np.array([2,3,1,2,3,4])
b

array([2, 3, 1, 2, 3, 4])

In [ ]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [ ]:
b

array([2, 3, 1, 2, 3, 4])

In [ ]:
a+10

array([[14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [ ]:
a+b

# broadcasrt operation row wise

array([[ 6,  8,  7,  9, 11, 13],
       [12, 14, 13, 15, 17, 19],
       [18, 20, 19, 21, 23, 25],
       [24, 26, 25, 27, 29, 31],
       [30, 32, 31, 33, 35, 37],
       [36, 38, 37, 39, 41, 43]])

In [ ]:
# performing broadcasting operation columnwise
b.shape

(6,)

In [ ]:
b = b.reshape(1,-1)   # instade of this we aN ALSO USE b.reshape(-1,1)
b

array([[2, 3, 1, 2, 3, 4]])

In [ ]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [ ]:
b.shape

(1, 6)

In [ ]:
b.T +a

array([[ 6,  7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17, 18],
       [17, 18, 19, 20, 21, 22],
       [24, 25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35, 36],
       [38, 39, 40, 41, 42, 43]])

In [ ]:
#########################################

In [ ]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [ ]:
b

array([[2, 3, 1, 2, 3, 4]])

In [ ]:
b = b.reshape(6,1)
b

array([[2],
       [3],
       [1],
       [2],
       [3],
       [4]])

In [ ]:
a+b

array([[ 6,  7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17, 18],
       [17, 18, 19, 20, 21, 22],
       [24, 25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35, 36],
       [38, 39, 40, 41, 42, 43]])

In [ ]:
a+b.T

array([[ 6,  8,  7,  9, 11, 13],
       [12, 14, 13, 15, 17, 19],
       [18, 20, 19, 21, 23, 25],
       [24, 26, 25, 27, 29, 31],
       [30, 32, 31, 33, 35, 37],
       [36, 38, 37, 39, 41, 43]])

In [ ]:
# squre root of array

print(a)
print(np.sqrt(a))

[[ 4  5  6  7  8  9]
 [10 11 12 13 14 15]
 [16 17 18 19 20 21]
 [22 23 24 25 26 27]
 [28 29 30 31 32 33]
 [34 35 36 37 38 39]]
[[2.         2.23606798 2.44948974 2.64575131 2.82842712 3.        ]
 [3.16227766 3.31662479 3.46410162 3.60555128 3.74165739 3.87298335]
 [4.         4.12310563 4.24264069 4.35889894 4.47213595 4.58257569]
 [4.69041576 4.79583152 4.89897949 5.         5.09901951 5.19615242]
 [5.29150262 5.38516481 5.47722558 5.56776436 5.65685425 5.74456265]
 [5.83095189 5.91607978 6.         6.08276253 6.164414   6.244998  ]]


In [ ]:
np.sqrt(b)

array([[1.41421356],
       [1.73205081],
       [1.        ],
       [1.41421356],
       [1.73205081],
       [2.        ]])

In [ ]:
np.exp(a)

array([[5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
        4.85165195e+08, 1.31881573e+09],
       [3.58491285e+09, 9.74480345e+09, 2.64891221e+10, 7.20048993e+10,
        1.95729609e+11, 5.32048241e+11],
       [1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
        7.89629602e+13, 2.14643580e+14],
       [5.83461743e+14, 1.58601345e+15, 4.31123155e+15, 1.17191424e+16,
        3.18559318e+16, 8.65934004e+16]])

In [ ]:
np.log10(a)

array([[0.60205999, 0.69897   , 0.77815125, 0.84509804, 0.90308999,
        0.95424251],
       [1.        , 1.04139269, 1.07918125, 1.11394335, 1.14612804,
        1.17609126],
       [1.20411998, 1.23044892, 1.25527251, 1.2787536 , 1.30103   ,
        1.32221929],
       [1.34242268, 1.36172784, 1.38021124, 1.39794001, 1.41497335,
        1.43136376],
       [1.44715803, 1.462398  , 1.47712125, 1.49136169, 1.50514998,
        1.51851394],
       [1.53147892, 1.54406804, 1.5563025 , 1.56820172, 1.5797836 ,
        1.59106461]])

In [ ]:
########################################

In [ ]:
x = np.array([1,2,3])  # Original
x

array([1, 2, 3])

In [ ]:
y = x  # shalow copy
y

array([1, 2, 3])

In [ ]:
z = np.copy(x)   # deep copy
z

array([1, 2, 3])

In [ ]:
x[0] = 100

In [ ]:
y  # shalow copy changes with the original copy
# it refers to the same memory locationand does not make new space

array([100,   2,   3])

In [ ]:
z   # deep copy keep the static data that was true when the copy was made
#      this makes a seperate space
#      it does not refer to the same location as the original location
#     newly made changes are not reflected inthis copy
# it is called deep copy coz it permently copies the data tyoi new location and
# thee are no dependencies %%

array([1, 2, 3])

In [ ]:
####################################

In [ ]:
# id() funciton

In [ ]:
id(x)

133557349314224

In [ ]:
id(y)

133557349314224

In [ ]:
# id() : it gives us the identity of an object
# this is a guarantee to be unique among simultaneously existing objects
# it does not refer to the memory locaiton

In [ ]:
x

array([100,   2,   3])

In [ ]:
id(x[0])

133557347490352

In [ ]:
id(y[0])

133557347486832

In [ ]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [ ]:
y = x

In [ ]:
id(x)

133557348968720

In [ ]:
id(y)

133557348968720

In [ ]:
# both above are same

In [ ]:
id(x[0])

133557348988624

In [ ]:
id(y[0])

133557348983888

In [ ]:
# element wise it is different though

In [ ]:
id(x[0]) == id(y[0])

# like what's going on :(

True

In [ ]:
id(x) == id(y)

True